# Generated by Django 3.0.5 on 2020-07-13 15:33

# import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('address', '0002_auto_20160213_1726'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, default='', max_length=30, verbose_name='Your Organization')),
                ('org_desc', models.TextField(blank=True, max_length=500)),
                ('org_phone', models.CharField(blank=True, max_length=17, verbose_name='phone')),
                ('org_email', models.EmailField(max_length=254, unique=True, verbose_name='Your Organizations Email')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('associated_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                # ('org_address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address')),
            ],
        ),
    ]
