# Generated by Django 3.0.4 on 2020-04-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('org_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AreaMap',
        ),
    ]
