# Generated by Django 3.0.5 on 2020-07-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200713_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='associated_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_email',
            field=models.EmailField(max_length=254, verbose_name='Your Organizations Email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Your Organization'),
        ),
    ]
