# Generated by Django 3.0.5 on 2020-07-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200713_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='main\\static\\images\\default.png', upload_to='profile_pics'),
        ),
    ]
