# Generated by Django 3.0.5 on 2020-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200713_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Donor'), (2, 'Recipient'), (3, 'Both')], null=True),
        ),
    ]
