# Generated by Django 3.0.5 on 2020-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_org_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_role',
            field=models.CharField(choices=[('Donor', 'DONOR'), ('Recipient', 'RECIPIENT'), ('Both', 'BOTH')], default='Donor', max_length=9),
        ),
    ]
