# Generated by Django 3.0.5 on 2020-07-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200714_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_role',
            field=models.CharField(choices=[('D', 'Donor'), ('R', 'Recipient'), ('B', 'Both')], default='D', max_length=1),
        ),
    ]
