# Generated by Django 3.0.5 on 2020-07-15 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200714_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='org_address',
            new_name='address',
        ),
    ]
