# Generated by Django 3.0.5 on 2020-07-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200715_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='profile',
            name='org_address',
            field=models.CharField(default='123 Test St.', max_length=80, verbose_name='Your Organizations Location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_city',
            field=models.CharField(default='Stamford', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_country',
            field=models.CharField(default='USA', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_state',
            field=models.CharField(default='CT', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_zipcode',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
