# Generated by Django 3.0.5 on 2020-07-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200715_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='org_name',
            new_name='your_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_zipcode',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
