# Generated by Django 3.0.5 on 2020-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200715_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='your_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='user name'),
        ),
    ]
