# Generated by Django 3.0.5 on 2020-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200716_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_phone',
            field=models.IntegerField(blank=True, verbose_name='phone'),
        ),
    ]
