# Generated by Django 3.0.5 on 2020-07-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200716_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='phone'),
        ),
    ]
