# Generated by Django 3.0.5 on 2020-07-27 19:33

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200716_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics', validators=[main.validators.validate_is_pic], verbose_name='Profile Image'),
        ),
    ]
