# Generated by Django 3.0.5 on 2020-08-19 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200817_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_day', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'MONDAY'), ('Tu', 'TUESDAY'), ('W', 'WEDNESDAY'), ('Th', 'THURSDAY'), ('F', 'FRIDAY'), ('Sa', 'SATURDAY'), ('Su', 'SUNDAY')], max_length=10)),
                ('start_hour', models.TimeField(null=True)),
                ('end_hour', models.TimeField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='donorrepeatingpost',
            old_name='recurrences',
            new_name='recurrences_test',
        ),
        migrations.RenameField(
            model_name='recipientrepeatingpost',
            old_name='recurrences',
            new_name='recurrences_test',
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='recurrences',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_begin_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Availability Start'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_creator',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Availability End'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_title',
            field=models.CharField(blank=True, max_length=30, verbose_name='Post Title'),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_avail',
            field=models.ManyToManyField(to='main.Availability'),
        ),
    ]
