# Generated by Django 3.0.5 on 2020-08-19 22:00

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20200819_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='post_avail',
        ),
        migrations.AddField(
            model_name='availability',
            name='assigned_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserPost'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='post_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Mon'), ('tu', 'Tue'), ('w', 'Wed'), ('th', 'Thu'), ('f', 'Fri'), ('sa', 'Sat'), ('su', 'Sun')], max_length=10),
        ),
    ]
