# Generated by Django 3.0.5 on 2020-08-20 21:18

from django.db import migrations, models
import main.validators
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200819_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='post_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Mon'), ('tu', 'Tue'), ('w', 'Wed'), ('th', 'Thu'), ('f', 'Fri'), ('sa', 'Sat'), ('su', 'Sun')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics', validators=[main.validators.validate_is_pic], verbose_name='Profile Image'),
        ),
    ]
