# Generated by Django 3.0.5 on 2020-08-21 14:33

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_userpost_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics', validators=[main.validators.validate_is_pic], verbose_name='Profile Image'),
        ),
    ]
