# Generated by Django 3.0.5 on 2020-08-24 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_userpost_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='post_long',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='assigned_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='main.UserPost'),
        ),
    ]
