# Generated by Django 3.0.5 on 2020-08-24 16:25

from django.db import migrations, models
import django.db.models.deletion
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200824_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='assigned_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserPost'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='post_pics', validators=[main.validators.validate_is_pic], verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
