# Generated by Django 3.0.5 on 2020-08-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200824_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_slug',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_deliver',
            field=models.BooleanField(default=False),
        ),
    ]
