# Generated by Django 3.0.5 on 2020-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200825_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
        ),
    ]
