# Generated by Django 3.0.5 on 2020-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200826_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
