# Generated by Django 3.0.5 on 2020-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200826_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
